env:
  global:
  - COMMIT_AUTHOR_NAME="Travis CI"
  - COMMIT_AUTHOR_EMAIL="dolphin.w.e@gmail.com"
language: node_js
node_js:
- stable
before_install:
- chmod +x ./scripts/deploy.sh
script: npm run deploy
